ADP_TO_TARTAN_FIELD_MAP = {
    "employeeId": "employee_number",
    "firstName": "first_name",
    "middleInitial": "middle_name",
    "lastName": "last_name",
    "preferredName": "preferred_name",
    "email": "work_email",
    "personalEmail": "personal_email",
    "workPhone": "mobile_phone_number",
    "managerId": "manager_id",
    "managerName": "manager_name",
    "payGroup": "pay_group",
    "ssn": "ssn",
    "gender": "gender",
    "ethnicity": "ethnicity",
    "maritalStatus": "marital_status",
    "dob": "date_of_birth",
    "startDate": "start_date",
    "remoteCreatedAt": "remote_created_at",
    "employmentStatus": "employment_status",
    "terminationDate": "termination_date",
    "avatar": "avatar",
    "departmentName": "department",
    "location": "work_location",

    "company.legalName": "company.legal_name",
    "company.displayName": "company.display_name",
    "company.location": "company.location",
    "company.ein": "company.eins[0]",

    "employments[0].jobTitle": "employments[0].job_title",
    "employments[0].payRate": "employments[0].pay_rate",
    "employments[0].payPeriod": "employments[0].pay_period",
    "employments[0].payFrequency": "employments[0].pay_frequency",
    "employments[0].currency": "employments[0].pay_currency",
    "employments[0].flsaStatus": "employments[0].flsa_status",
    "employments[0].effectiveDate": "employments[0].effective_date",
    "employments[0].employmentType": "employments[0].employment_type",

    "salaries[0].payDate": "salaries[0].pay_date",
    "salaries[0].startDate": "salaries[0].start_date",
    "salaries[0].endDate": "salaries[0].end_date",
    "salaries[0].totalHours": "salaries[0].total_hours",
    "salaries[0].payFrequency": "salaries[0].pay_frequency",
    "salaries[0].salaryType": "salaries[0].salary_type",
    "salaries[0].salaryMethod": "salaries[0].salary_method",
    "salaries[0].grossPay": "salaries[0].gross_pay_details.base",
    "salaries[0].bonus": "salaries[0].gross_pay_details.bonus",
    "salaries[0].overtime": "salaries[0].gross_pay_details.overtime",
    "salaries[0].netPay": "salaries[0].net_pay_details.amount",
    "salaries[0].currency": "salaries[0].net_pay_details.currency",
    "salaries[0].deductions[0].type": "salaries[0].deduction_details[0].type",
    "salaries[0].deductions[0].amount": "salaries[0].deduction_details[0].amount",
    "salaries[0].contributions[0].type": "salaries[0].contribution_details[0].type",
    "salaries[0].contributions[0].amount": "salaries[0].contribution_details[0].amount",
    "salaries[0].taxes[0].type": "salaries[0].tax_details[0].type",
    "salaries[0].taxes[0].amount": "salaries[0].tax_details[0].amount",

    "benefits[0].providerName": "benefits[0].provider_name",
    "benefits[0].employeeContribution": "benefits[0].employee_contribution",
    "benefits[0].companyContribution": "benefits[0].company_contribution",
    "benefits[0].startDate": "benefits[0].start_date",
    "benefits[0].endDate": "benefits[0].end_date",
    "benefits[0].planName": "benefits[0].employer_benefit",

    "homeLocation.name": "locations.home.name",
    "homeLocation.phone": "locations.home.phone_number",
    "homeLocation.street1": "locations.home.street_1",
    "homeLocation.street2": "locations.home.street_2",
    "homeLocation.city": "locations.home.city",
    "homeLocation.state": "locations.home.state",
    "homeLocation.zip": "locations.home.zip_code",
    "homeLocation.country": "locations.home.country",

    "workLocation.name": "locations.work.name",
    "workLocation.phone": "locations.work.phone_number",
    "workLocation.street1": "locations.work.street_1",
    "workLocation.street2": "locations.work.street_2",
    "workLocation.city": "locations.work.city",
    "workLocation.state": "locations.work.state",
    "workLocation.zip": "locations.work.zip_code",
    "workLocation.country": "locations.work.country",
}
